using System;
using System.Runtime.InteropServices;
using System.Text;

namespace Avalonia.Wayland.Embedding.Compositor;

/// <summary>
/// Supplies an <c>xkb_v1</c> keymap for wl_keyboard.keymap. Defaults to an en-US keymap generated by the host
/// libxkbcommon (D1), overridable via <see cref="WaylandEmbeddingSubcompositor.KeymapTextProvider"/>. The text
/// is cached; <see cref="CreateFd"/> materializes it as a memfd whose ownership transfers to NWayland when
/// passed to <c>WlKeyboard.Server.Keymap</c> (NWayland closes the fd after the SCM_RIGHTS send). Compositor-thread only.
/// </summary>
internal static class XkbKeymap
{
    private static string? s_cached;

    public static string GetText()
    {
        if (WaylandEmbeddingSubcompositor.KeymapTextProvider is { } provider)
            return provider();
        return s_cached ??= GenerateEnUs() ?? FallbackKeymap;
    }

    /// <summary>Create a memfd holding the keymap text (NUL-terminated). Returns the fd; <paramref name="size"/>
    /// includes the trailing NUL. The fd's ownership transfers to the caller (and then to NWayland on send).</summary>
    public static int CreateFd(out uint size)
    {
        var bytes = Encoding.UTF8.GetBytes(GetText());
        size = (uint)(bytes.Length + 1); // wl_keyboard.keymap size counts the trailing NUL

        var fd = MemfdCreate("wlembed-keymap", MfdCloexec | MfdAllowSealing);
        if (fd < 0)
            throw new InvalidOperationException($"memfd_create failed: errno {Marshal.GetLastPInvokeError()}");
        if (Ftruncate(fd, size) != 0)
        {
            Close(fd);
            throw new InvalidOperationException($"ftruncate failed: errno {Marshal.GetLastPInvokeError()}");
        }
        var addr = Mmap(IntPtr.Zero, size, ProtRead | ProtWrite, MapShared, fd, 0);
        if (addr == new IntPtr(-1))
        {
            Close(fd);
            throw new InvalidOperationException($"mmap failed: errno {Marshal.GetLastPInvokeError()}");
        }
        Marshal.Copy(bytes, 0, addr, bytes.Length);
        Marshal.WriteByte(addr, bytes.Length, 0);
        Munmap(addr, size);
        Fcntl(fd, FAddSeals, FSealShrink | FSealWrite); // best-effort: hand the client an immutable keymap
        return fd;
    }

    private static string? GenerateEnUs()
    {
        try
        {
            var ctx = xkb_context_new(0);
            if (ctx == IntPtr.Zero)
                return null;
            try
            {
                var names = default(XkbRuleNames); // all-NULL ⇒ defaults: rules=evdev, model=pc105, layout=us
                var keymap = xkb_keymap_new_from_names(ctx, ref names, 0);
                if (keymap == IntPtr.Zero)
                    return null;
                try
                {
                    var ptr = xkb_keymap_get_as_string(keymap, 1 /* XKB_KEYMAP_FORMAT_TEXT_V1 */);
                    if (ptr == IntPtr.Zero)
                        return null;
                    try { return Marshal.PtrToStringUTF8(ptr); }
                    finally { Free(ptr); }
                }
                finally { xkb_keymap_unref(keymap); }
            }
            finally { xkb_context_unref(ctx); }
        }
        catch (DllNotFoundException) { return null; }
        catch (EntryPointNotFoundException) { return null; }
    }

    // Used only if libxkbcommon is unavailable; real toolkits rely on the xkbcommon path above.
    private const string FallbackKeymap =
        "xkb_keymap {\n" +
        "  xkb_keycodes  { include \"evdev+aliases(qwerty)\" };\n" +
        "  xkb_types     { include \"complete\" };\n" +
        "  xkb_compat    { include \"complete\" };\n" +
        "  xkb_symbols   { include \"pc+us+inet(evdev)\" };\n" +
        "};\n";

    [StructLayout(LayoutKind.Sequential)]
    private struct XkbRuleNames
    {
        public IntPtr Rules, Model, Layout, Variant, Options;
    }

    private const int ProtRead = 0x1, ProtWrite = 0x2, MapShared = 0x1;
    private const uint MfdCloexec = 0x1, MfdAllowSealing = 0x2;
    private const int FAddSeals = 1033, FSealShrink = 0x2, FSealWrite = 0x8;

    [DllImport("libxkbcommon.so.0")] private static extern IntPtr xkb_context_new(int flags);
    [DllImport("libxkbcommon.so.0")] private static extern IntPtr xkb_keymap_new_from_names(IntPtr ctx, ref XkbRuleNames names, int flags);
    [DllImport("libxkbcommon.so.0")] private static extern IntPtr xkb_keymap_get_as_string(IntPtr keymap, int format);
    [DllImport("libxkbcommon.so.0")] private static extern void xkb_keymap_unref(IntPtr keymap);
    [DllImport("libxkbcommon.so.0")] private static extern void xkb_context_unref(IntPtr ctx);

    [DllImport("libc", EntryPoint = "free")] private static extern void Free(IntPtr ptr);
    [DllImport("libc", EntryPoint = "memfd_create", SetLastError = true)] private static extern int MemfdCreate(string name, uint flags);
    [DllImport("libc", EntryPoint = "ftruncate", SetLastError = true)] private static extern int Ftruncate(int fd, long length);
    [DllImport("libc", EntryPoint = "mmap", SetLastError = true)] private static extern IntPtr Mmap(IntPtr addr, nuint length, int prot, int flags, int fd, long offset);
    [DllImport("libc", EntryPoint = "munmap", SetLastError = true)] private static extern int Munmap(IntPtr addr, nuint length);
    [DllImport("libc", EntryPoint = "close", SetLastError = true)] private static extern int Close(int fd);
    [DllImport("libc", EntryPoint = "fcntl", SetLastError = true)] private static extern int Fcntl(int fd, int cmd, int arg);
}
