namespace Avalonia.OpenGL.Egl
{
    public enum EglErrors
    {
        EGL_SUCCESS = EglConsts.EGL_SUCCESS,
        EGL_NOT_INITIALIZED = EglConsts.EGL_NOT_INITIALIZED,
        EGL_BAD_ACCESS = EglConsts.EGL_BAD_ACCESS,
        EGL_BAD_ALLOC = EglConsts.EGL_BAD_ALLOC,
        EGL_BAD_ATTRIBUTE = EglConsts.EGL_BAD_ATTRIBUTE,
        EGL_BAD_CONTEXT = EglConsts.EGL_BAD_CONTEXT,
        EGL_BAD_CONFIG = EglConsts.EGL_BAD_CONFIG,
        EGL_BAD_CURRENT_SURFACE = EglConsts.EGL_BAD_CURRENT_SURFACE,
        EGL_BAD_DISPLAY = EglConsts.EGL_BAD_DISPLAY,
        EGL_BAD_SURFACE = EglConsts.EGL_BAD_SURFACE,
        EGL_BAD_MATCH = EglConsts.EGL_BAD_MATCH,
        EGL_BAD_PARAMETER = EglConsts.EGL_BAD_PARAMETER,
        EGL_BAD_NATIVE_PIXMAP = EglConsts.EGL_BAD_NATIVE_PIXMAP,
        EGL_BAD_NATIVE_WINDOW = EglConsts.EGL_BAD_NATIVE_WINDOW,
        EGL_CONTEXT_LOST = EglConsts.EGL_CONTEXT_LOST
    }
}
