using System.Collections.Generic;
using System.IO;
using System.Text.RegularExpressions;
using Avalonia.Media.TextFormatting.Unicode;

namespace Avalonia.UnicodeTrieGenerator;

internal static class UnicodeDataGenerator
{
    public static UnicodeTrie GenerateBiDiTrie(
        string outputDir,
        out BiDiDataEntries biDiDataEntries,
        out Dictionary<int, BiDiDataItem> biDiData)
    {
        biDiData = new Dictionary<int, BiDiDataItem>();

        var bidiClassEntries = UnicodeEnumsGenerator.CreateBidiClassEnum(outputDir);
        var bidiClassMappings = CreateTagToIndexMappings(bidiClassEntries);
        var bidiClassData = ReadBiDiData();

        foreach (var (range, name) in bidiClassData)
        {
            var biDiClass = bidiClassMappings[name];
            AddBiDiClassRange(biDiData, range, biDiClass);
        }

        var biDiPairedBracketTypeEntries = UnicodeEnumsGenerator.CreateBiDiPairedBracketTypeEnum(outputDir);
        var biDiPairedBracketTypeMappings = CreateTagToIndexMappings(biDiPairedBracketTypeEntries);
        var biDiPairedBracketData = ReadBiDiPairedBracketData();

        foreach (var (range, name) in biDiPairedBracketData)
        {
            var bracketType = biDiPairedBracketTypeMappings[name];
            AddBiDiBracket(biDiData, range, bracketType);
        }

        // After moving away from seeded enum entries the default int positions of
        // BidiClass.LeftToRight and BidiPairedBracketType.None are no longer 0,
        // so an unset trie slot would otherwise resolve to whichever class lands
        // at index 0 in UCD's alphabetical-by-tag ordering. Pack the real defaults
        // explicitly: LeftToRight bidi class, None bracket type, no paired bracket.
        var initialBiDiValue = ((uint)bidiClassMappings["L"] << UnicodeData.BIDICLASS_SHIFT) |
                               ((uint)biDiPairedBracketTypeMappings["n"] << UnicodeData.BIDIPAIREDBRACKEDTYPE_SHIFT);
        var biDiTrieBuilder = new UnicodeTrieBuilder(initialBiDiValue);

        foreach (var properties in biDiData.Values)
        {
            //[bracket]|[bracketType]|[biDiClass]
            var value = (properties.BiDiClass << UnicodeData.BIDICLASS_SHIFT) |
                        (properties.BracketType << UnicodeData.BIDIPAIREDBRACKEDTYPE_SHIFT) | properties.Bracket;

            biDiTrieBuilder.Set(properties.Codepoint, (uint)value);
        }

        biDiDataEntries = new BiDiDataEntries
        {
            PairedBracketTypes = biDiPairedBracketTypeEntries,
            BiDiClasses = bidiClassEntries
        };

        var trie = biDiTrieBuilder.Freeze();

        GenerateTrieClass(outputDir, "BiDi", trie);

        return trie;
    }

    public static void GenerateTrieClass(string outputDir, string name, UnicodeTrie trie)
    {
        using var fileStream = File.Create(Path.Combine(outputDir, $"{name}.trie.cs"));
        using var writer = new StreamWriter(fileStream);

        writer.Write(
            ($$"""
               //---------------------------------------------------------------------------------------------------
               // <auto-generated>
               //     This code was generated by UnicodeDataGenerator.
               //     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
               // </auto-generated>"
               //---------------------------------------------------------------------------------------------------

               using System;
               using System.Runtime.CompilerServices;

               namespace Avalonia.Media.TextFormatting.Unicode;

               internal static class {{name}}Trie
               {
                   public static UnicodeTrie Trie
                   {
                       [MethodImpl(MethodImplOptions.AggressiveInlining)]
                       get => new(Data, 0x{{trie.HighStart:X8}}, 0x{{trie.ErrorValue:X8}});
                   }

                   // For Debug builds, we store the data in a separate uint[] field to avoid RuntimeFieldInfoStub allocations.
                   // See also: https://github.com/AvaloniaUI/Avalonia/pull/20175

               #if DEBUG
                   public static ReadOnlySpan<uint> Data => s_data;
                   private static uint[] s_data =
               #else
                   public static ReadOnlySpan<uint> Data =>
               #endif
                   [
               """).ReplaceLineEndings());

        for (int i = 0; i < trie.Data.Length; ++i)
        {
            if (i > 0)
                writer.Write(", ");

            if (i % 12 == 0)
            {
                writer.WriteLine();
                writer.Write("        ");
            }

            writer.Write("0x");
            writer.Write(trie.Data[i].ToString("X8"));
        }

        writer.Write(
            ("""

                 ];
             }

             """).ReplaceLineEndings());
    }

    public static UnicodeTrie GenerateUnicodeDataTrie(
        string outputDir,
        out UnicodeDataEntries dataEntries,
        out Dictionary<int, UnicodeDataItem> unicodeData)
    {
        var generalCategoryEntries = UnicodeEnumsGenerator.CreateGeneralCategoryEnum(outputDir);
        var generalCategoryMappings = CreateTagToIndexMappings(generalCategoryEntries);

        var scriptEntries = UnicodeEnumsGenerator.CreateScriptEnum(outputDir);
        var scriptMappings = CreateNameToIndexMappings(scriptEntries);

        var lineBreakClassEntries = UnicodeEnumsGenerator.CreateLineBreakClassEnum(outputDir);
        var lineBreakClassMappings = CreateNameAndTagToIndexMappings(lineBreakClassEntries);

        var wordBreakClassEntries = UnicodeEnumsGenerator.CreateWordBreakClassEnum(outputDir);
        var wordBreakClassMappings = CreateNameAndTagToIndexMappings(wordBreakClassEntries);

        unicodeData = GetUnicodeData(
            generalCategoryMappings,
            scriptMappings,
            lineBreakClassMappings,
            wordBreakClassMappings);

        // Unassigned code points are not listed in every UCD file, so the trie
        // default must match the explicit fallback classes rather than enum zero.
        var initialValue = lineBreakClassMappings["XX"] << UnicodeData.LINEBREAK_SHIFT;
        var unicodeDataTrieBuilder = new UnicodeTrieBuilder((uint)initialValue);

        foreach (var properties in unicodeData.Values)
        {
            //[word break]|[line break]|[biDi]|[script]|[category]
            var value = (properties.WordBreakClass << UnicodeData.WORDBREAK_SHIFT) |
                        (properties.LineBreakClass << UnicodeData.LINEBREAK_SHIFT) |
                        (properties.Script << UnicodeData.SCRIPT_SHIFT) | properties.GeneralCategory;

            unicodeDataTrieBuilder.Set(properties.Codepoint, (uint)value);
        }

        dataEntries = new UnicodeDataEntries
        {
            Scripts = scriptEntries,
            GeneralCategories = generalCategoryEntries,
            LineBreakClasses = lineBreakClassEntries,
            WordBreakClasses = wordBreakClassEntries
        };

        var trie = unicodeDataTrieBuilder.Freeze();

        GenerateTrieClass(outputDir, "UnicodeData", trie);

        return trie;
    }

    private static Dictionary<int, UnicodeDataItem> GetUnicodeData(
        IReadOnlyDictionary<string, int> generalCategoryMappings,
        IReadOnlyDictionary<string, int> scriptMappings,
        IReadOnlyDictionary<string, int> lineBreakClassMappings,
        IReadOnlyDictionary<string, int> wordBreakClassMappings)
    {
        var unicodeData = new Dictionary<int, UnicodeDataItem>();

        foreach (var (range, name) in ReadGeneralCategoryData())
        {
            var generalCategory = generalCategoryMappings[name];
            AddGeneralCategoryRange(unicodeData, range, generalCategory);
        }

        foreach (var (range, name) in ReadScriptData())
        {
            var script = scriptMappings[name];
            AddScriptRange(unicodeData, range, script);
        }

        foreach (var (range, name) in ReadLineBreakClassData())
        {
            var lineBreakClass = lineBreakClassMappings[name];
            AddLineBreakClassRange(unicodeData, range, lineBreakClass);
        }

        foreach (var (range, name) in ReadWordBreakClassData())
        {
            var wordBreakClass = wordBreakClassMappings[name];
            AddWordBreakClassRange(unicodeData, range, wordBreakClass);
        }

        foreach (var properties in unicodeData.Values)
        {
            if (properties.LineBreakClass < 0)
            {
                properties.LineBreakClass = lineBreakClassMappings["XX"];
            }

            if (properties.WordBreakClass < 0)
            {
                properties.WordBreakClass = wordBreakClassMappings["Other"];
            }
        }

        return unicodeData;
    }

    public static Dictionary<string, int> CreateTagToIndexMappings(IReadOnlyList<DataEntry> entries)
    {
        var mappings = new Dictionary<string, int>();

        for (var i = 0; i < entries.Count; i++)
        {
            mappings.Add(entries[i].Tag, i);
        }

        return mappings;
    }

    public static Dictionary<string, int> CreateNameToIndexMappings(IReadOnlyList<DataEntry> entries)
    {
        var mappings = new Dictionary<string, int>();

        for (var i = 0; i < entries.Count; i++)
        {
            mappings.Add(entries[i].Name, i);
        }

        return mappings;
    }

    public static Dictionary<string, int> CreateNameAndTagToIndexMappings(IReadOnlyList<DataEntry> entries)
    {
        var mappings = new Dictionary<string, int>();

        for (var i = 0; i < entries.Count; i++)
        {
            mappings[entries[i].Name] = i;
            mappings[entries[i].Name.Replace("_", "")] = i;
            mappings[entries[i].Tag] = i;
        }

        return mappings;
    }

    private static void AddGeneralCategoryRange(Dictionary<int, UnicodeDataItem> codepoints, CodepointRange range, int generalCategory)
    {
        for (var i = range.Start; i <= range.End; i++)
        {
            if (!codepoints.ContainsKey(i))
            {
                codepoints.Add(i, new UnicodeDataItem { Codepoint = i, GeneralCategory = generalCategory });
            }
            else
            {
                codepoints[i].GeneralCategory = generalCategory;
            }
        }
    }

    private static void AddScriptRange(Dictionary<int, UnicodeDataItem> codepoints, CodepointRange range, int script)
    {
        for (var i = range.Start; i <= range.End; i++)
        {
            if (!codepoints.ContainsKey(i))
            {
                codepoints.Add(i, new UnicodeDataItem { Codepoint = i, Script = script });
            }
            else
            {
                codepoints[i].Script = script;
            }
        }
    }

    private static void AddBiDiClassRange(Dictionary<int, BiDiDataItem> codepoints, CodepointRange range, int biDiClass)
    {
        for (var i = range.Start; i <= range.End; i++)
        {
            if (!codepoints.ContainsKey(i))
            {
                codepoints.Add(i, new BiDiDataItem { Codepoint = i, BiDiClass = biDiClass });
            }
            else
            {
                codepoints[i].BiDiClass = biDiClass;
            }
        }
    }

    private static void AddBiDiBracket(Dictionary<int, BiDiDataItem> codepoints, CodepointRange range, int bracketType)
    {
        if (!codepoints.ContainsKey(range.Start))
        {
            codepoints.Add(range.Start,
                new BiDiDataItem { Codepoint = range.Start, Bracket = range.End, BracketType = bracketType });
        }
        else
        {
            var codepoint = codepoints[range.Start];
            codepoint.Bracket = range.End;
            codepoint.BracketType = bracketType;
        }
    }

    private static void AddLineBreakClassRange(Dictionary<int, UnicodeDataItem> codepoints, CodepointRange range, int lineBreakClass)
    {
        for (var i = range.Start; i <= range.End; i++)
        {
            if (!codepoints.ContainsKey(i))
            {
                codepoints.Add(i, new UnicodeDataItem { Codepoint = i, LineBreakClass = lineBreakClass });
            }
            else
            {
                codepoints[i].LineBreakClass = lineBreakClass;
            }
        }
    }

    private static void AddWordBreakClassRange(Dictionary<int, UnicodeDataItem> codepoints, CodepointRange range, int wordBreakClass)
    {
        for (var i = range.Start; i <= range.End; i++)
        {
            if (!codepoints.ContainsKey(i))
            {
                codepoints.Add(i, new UnicodeDataItem { Codepoint = i, WordBreakClass = wordBreakClass });
            }
            else
            {
                codepoints[i].WordBreakClass = wordBreakClass;
            }
        }
    }

    public static List<(CodepointRange, string)> ReadGeneralCategoryData()
        => ReadUnicodeData("extracted/DerivedGeneralCategory.txt");

    public static List<(CodepointRange, string)> ReadScriptData()
        => ReadUnicodeData("Scripts.txt");

    public static List<(CodepointRange, string)> ReadBiDiData()
        => ReadUnicodeData("extracted/DerivedBidiClass.txt");

    public static List<(CodepointRange, string)> ReadLineBreakClassData()
    {
        const string file = "extracted/DerivedLineBreak.txt";

        var data = ReadMissingUnicodeData(file);

        data.AddRange(ReadUnicodeData(file));

        return data;
    }

    public static List<(CodepointRange, string)> ReadWordBreakClassData()
        => ReadUnicodeData("auxiliary/WordBreakProperty.txt");

    public static List<(CodepointRange, string)> ReadBiDiPairedBracketData()
    {
        var data = new List<(CodepointRange, string)>();
        var regex = new Regex(@"^([0-9A-F]+);\s([0-9A-F]+);\s([ocn])");

        using var stream = UcdDownloader.OpenRead("BidiBrackets.txt");
        using var reader = new StreamReader(stream);

        while (!reader.EndOfStream)
        {
            var line = reader.ReadLine();

            if (string.IsNullOrEmpty(line))
            {
                continue;
            }

            var match = regex.Match(line);

            if (!match.Success)
            {
                continue;
            }

            var start = System.Convert.ToInt32(match.Groups[1].Value, 16);
            var end = start;

            if (!string.IsNullOrEmpty(match.Groups[2].Value))
            {
                end = System.Convert.ToInt32(match.Groups[2].Value, 16);
            }

            data.Add((new CodepointRange(start, end), match.Groups[3].Value));
        }

        return data;
    }

    private static List<(CodepointRange, string)> ReadUnicodeData(string file)
    {
        var data = new List<(CodepointRange, string)>();
        var regex = new Regex(@"([0-9A-F]+)(?:\.\.([0-9A-F]+))?\s+;\s+(\w+)\s+#.*", RegexOptions.Compiled);

        using var stream = UcdDownloader.OpenRead(file);
        using var reader = new StreamReader(stream);

        while (!reader.EndOfStream)
        {
            var line = reader.ReadLine();

            if (string.IsNullOrEmpty(line))
            {
                continue;
            }

            var match = regex.Match(line);

            if (!match.Success)
            {
                continue;
            }

            var start = System.Convert.ToInt32(match.Groups[1].Value, 16);
            var end = start;

            if (!string.IsNullOrEmpty(match.Groups[2].Value))
            {
                end = System.Convert.ToInt32(match.Groups[2].Value, 16);
            }

            data.Add((new CodepointRange(start, end), match.Groups[3].Value));
        }

        return data;
    }

    private static List<(CodepointRange, string)> ReadMissingUnicodeData(string file)
    {
        var data = new List<(CodepointRange, string)>();
        var regex = new Regex(@"# @missing:\s+([0-9A-F]+)(?:\.\.([0-9A-F]+))?;\s+(\w+)", RegexOptions.Compiled);

        using var stream = UcdDownloader.OpenRead(file);
        using var reader = new StreamReader(stream);

        while (!reader.EndOfStream)
        {
            var line = reader.ReadLine();

            if (string.IsNullOrEmpty(line))
            {
                continue;
            }

            var match = regex.Match(line);

            if (!match.Success || match.Groups[3].Value == "Unknown")
            {
                continue;
            }

            var start = System.Convert.ToInt32(match.Groups[1].Value, 16);
            var end = start;

            if (!string.IsNullOrEmpty(match.Groups[2].Value))
            {
                end = System.Convert.ToInt32(match.Groups[2].Value, 16);
            }

            data.Add((new CodepointRange(start, end), match.Groups[3].Value));
        }

        return data;
    }

    internal class UnicodeDataItem
    {
        public int Codepoint { get; set; }
        public int Script { get; set; }
        public int GeneralCategory { get; set; }
        public int BiDiClass { get; set; }
        public int LineBreakClass { get; set; } = -1;
        public int WordBreakClass { get; set; } = -1;
    }

    internal class BiDiDataItem
    {
        public int Codepoint { get; set; }
        public int Bracket { get; set; }
        public int BracketType { get; set; }
        public int BiDiClass { get; set; }
    }
}

internal class UnicodeDataEntries
{
    public IReadOnlyList<DataEntry> Scripts { get; set; } = [];
    public IReadOnlyList<DataEntry> GeneralCategories { get; set; } = [];
    public IReadOnlyList<DataEntry> LineBreakClasses { get; set; } = [];
    public IReadOnlyList<DataEntry> WordBreakClasses { get; set; } = [];
}

internal class BiDiDataEntries
{
    public IReadOnlyList<DataEntry> PairedBracketTypes { get; set; } = [];
    public IReadOnlyList<DataEntry> BiDiClasses { get; set; } = [];
}

internal readonly struct CodepointRange
{
    public CodepointRange(int start, int end)
    {
        Start = start;
        End = end;
    }

    public int Start { get; }
    public int End { get; }
}
