using System;
using System.Diagnostics.CodeAnalysis;

// WARNING: Keep in sync with any `typeSystem.GetType(string)` usage in the compiler.
// If any type is missed here, runtime loader might crash due to trimmed types.

// ReSharper disable RedundantNameQualifier

namespace Avalonia.Markup.Xaml.XamlIl;

[AttributeUsage(AttributeTargets.Method, AllowMultiple = false)]
internal sealed class CompilerDynamicDependenciesAttribute : Attribute
{
    private const DynamicallyAccessedMemberTypes XamlAccessible = DynamicallyAccessedMemberTypes.All ^
        (DynamicallyAccessedMemberTypes.NonPublicConstructors
         | DynamicallyAccessedMemberTypes.NonPublicEvents
         | DynamicallyAccessedMemberTypes.NonPublicFields
         | DynamicallyAccessedMemberTypes.NonPublicMethods
         | DynamicallyAccessedMemberTypes.NonPublicProperties
         | DynamicallyAccessedMemberTypes.NonPublicNestedTypes);

    [DynamicDependency(XamlAccessible, typeof(Avalonia.Animation.Transitions))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.AttachedProperty<>))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.AvaloniaObject))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.AvaloniaObjectExtensions))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.AvaloniaProperty))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.AvaloniaProperty<>))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Collections.AvaloniaList<>))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Collections.AvaloniaListConverter<>))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Controls.Classes))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Controls.ColumnDefinition))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Controls.ColumnDefinitions))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Controls.Control))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Controls.GridLength))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Controls.GridUnitType))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Controls.INameScope))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Controls.IResourceDictionary))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Controls.IThemeVariantProvider))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Controls.ItemsControl))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Controls.NameScope))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Controls.ResourceDictionary))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Controls.RowDefinition))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Controls.RowDefinitions))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Controls.Templates.IDataTemplate))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Controls.WindowIcon))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Controls.WindowTransparencyLevel))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Data.AssignBindingAttribute))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Data.BindingPriority))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Data.Core.ClrPropertyInfo))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Data.Core.IPropertyInfo))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Data.Core.Plugins.IPropertyAccessor))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Data.Core.PropertyPath))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Data.Core.PropertyPathBuilder))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Data.IBinding))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Data.RelativeSource))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Input.Cursor))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Input.StandardCursorType))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Markup.Xaml.Converters.AvaloniaUriTypeConverter))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Markup.Xaml.Converters.BitmapTypeConverter))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Markup.Xaml.Converters.FontFamilyTypeConverter))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Markup.Xaml.Converters.IconTypeConverter))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Markup.Xaml.Converters.PointsListTypeConverter))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Markup.Xaml.Converters.TimeSpanTypeConverter))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Markup.Xaml.IProvideValueTarget))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Markup.Xaml.IRootObjectProvider))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Markup.Xaml.IUriContext))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Markup.Xaml.MarkupExtensions.CompiledBindingExtension))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Markup.Xaml.MarkupExtensions.CompiledBindings.CompiledBindingPath))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Markup.Xaml.MarkupExtensions.CompiledBindings.CompiledBindingPathBuilder))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Markup.Xaml.MarkupExtensions.CompiledBindings.PropertyInfoAccessorFactory))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Markup.Xaml.MarkupExtensions.On))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Markup.Xaml.MarkupExtensions.ReflectionBindingExtension))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Markup.Xaml.MarkupExtensions.ResolveByNameExtension))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Markup.Xaml.Styling.MergeResourceInclude))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Markup.Xaml.Styling.ResourceInclude))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Markup.Xaml.Styling.StyleInclude))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Markup.Xaml.Templates.DataTemplate))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlParentStackProvider))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Markup.Xaml.XamlIl.Runtime.XamlIlRuntimeHelpers))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Media.Color))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Media.FontFamily))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Media.IBrush))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Media.IImage))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Media.IImageBrushSource))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Media.Imaging.Bitmap))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Media.Immutable.ImmutableSolidColorBrush))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Media.TextDecorationCollection))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Media.TextDecorations))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Media.TextTrimming))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Metadata.AvaloniaListAttribute))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Metadata.ContentAttribute))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Metadata.DataTypeAttribute))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Metadata.DependsOnAttribute))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Metadata.IAddChild))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Metadata.IAddChild<>))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Metadata.InheritDataTypeFromItemsAttribute))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Metadata.MarkupExtensionDefaultOptionAttribute))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Metadata.MarkupExtensionOptionAttribute))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Metadata.TemplateContentAttribute))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Metadata.TrimSurroundingWhitespaceAttribute))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Metadata.UsableDuringInitializationAttribute))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Metadata.WhitespaceSignificantCollectionAttribute))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Metadata.XmlnsDefinitionAttribute))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Point))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.RelativePoint))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.RelativeUnit))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.StyledElement))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.StyledElementExtensions))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.StyledProperty<>))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Styling.ControlTheme))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Styling.IStyle))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Styling.Selectors))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Styling.SetterBase))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Styling.Style))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Styling.ThemeVariant))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.UnsetValueType))]
    [DynamicDependency(XamlAccessible, typeof(Avalonia.Utilities.TypeUtilities))]
    [DynamicDependency(XamlAccessible, typeof(System.ComponentModel.CultureInfoConverter))]
    [DynamicDependency(XamlAccessible, typeof(System.ComponentModel.ISupportInitialize))]
    [DynamicDependency(XamlAccessible, typeof(System.ComponentModel.ITypeDescriptorContext))]
    [DynamicDependency(XamlAccessible, typeof(System.ComponentModel.TypeConverterAttribute))]
    [DynamicDependency(XamlAccessible, typeof(System.Globalization.CultureInfo))]
    [DynamicDependency(XamlAccessible, typeof(System.IFormatProvider))]
    [DynamicDependency(XamlAccessible, typeof(System.IServiceProvider))]
    [DynamicDependency(XamlAccessible, typeof(System.Uri))]
    [DynamicDependency(XamlAccessible, typeof(System.UriKind))]
    [DynamicDependency(XamlAccessible, typeof(System.Windows.Input.ICommand))]
    public CompilerDynamicDependenciesAttribute()
    {
        
    }
}
