using System;

namespace Avalonia.Win32.DxgiSwapchain
{
    [Flags]
    public enum DXGI_SWAP_CHAIN_FLAG
    {
        DXGI_SWAP_CHAIN_FLAG_NONPREROTATED = 1,

        DXGI_SWAP_CHAIN_FLAG_ALLOW_MODE_SWITCH = 2,

        DXGI_SWAP_CHAIN_FLAG_GDI_COMPATIBLE = 4,

        DXGI_SWAP_CHAIN_FLAG_RESTRICTED_CONTENT = 8,

        DXGI_SWAP_CHAIN_FLAG_RESTRICT_SHARED_RESOURCE_DRIVER = 16,

        DXGI_SWAP_CHAIN_FLAG_DISPLAY_ONLY = 32,

        DXGI_SWAP_CHAIN_FLAG_FRAME_LATENCY_WAITABLE_OBJECT = 64,

        DXGI_SWAP_CHAIN_FLAG_FOREGROUND_LAYER = 128,

        DXGI_SWAP_CHAIN_FLAG_FULLSCREEN_VIDEO = 256,

        DXGI_SWAP_CHAIN_FLAG_YUV_VIDEO = 512,

        DXGI_SWAP_CHAIN_FLAG_HW_PROTECTED = 1024,

        DXGI_SWAP_CHAIN_FLAG_ALLOW_TEARING = 2048,

        DXGI_SWAP_CHAIN_FLAG_RESTRICTED_TO_ALL_HOLOGRAPHIC_DISPLAYS = 4096,
    }
#pragma warning restore CA1416 // Validate platform compatibility
#nullable restore
}
