using System.Collections.Generic;
using System.Linq;
using System.Text;
using Generator;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace DevGenerators;

[Generator(LanguageNames.CSharp)]
public class DefinitelyNotARecordGenerator : IIncrementalGenerator
{
    const string AttributeFullName = "global::Avalonia.SourceGenerator.DefinitelyNotARecordAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (s, _) => s is (ClassDeclarationSyntax or StructDeclarationSyntax)
                                 and TypeDeclarationSyntax
                                 {
                                     AttributeLists.Count: > 0,
                                     ParameterList: not null, // has a primary constructor
                                 } td
                                 && td.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword)),
                static (ctx, _) =>
                    (INamedTypeSymbol)ctx.SemanticModel.GetDeclaredSymbol(ctx.Node)!)
            .Where(s => s.HasAttributeWithFullyQualifiedName(AttributeFullName))
            .Collect();

        context.RegisterSourceOutput(candidates, static (context, types) =>
        {
            // The same partial type can be discovered through more than one declaration.
            foreach (var type in types.Distinct<INamedTypeSymbol>(SymbolEqualityComparer.Default).Cast<INamedTypeSymbol>())
                Generate(context, type);
        });
    }

    static void Generate(SourceProductionContext context, INamedTypeSymbol type)
    {
        var primaryCtor = type.InstanceConstructors.FirstOrDefault(c =>
            c.DeclaringSyntaxReferences.Any(r => r.GetSyntax() is TypeDeclarationSyntax));

        if (primaryCtor is null || primaryCtor.Parameters.Length == 0)
            return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");

        var ns = type.ContainingNamespace;
        if (ns is { IsGlobalNamespace: false })
            sb.Append("namespace ").Append(ns.ToDisplayString()).AppendLine();
        else
            sb.AppendLine();

        sb.AppendLine("{");

        // Re-open every enclosing type so the generated members land in the right nesting.
        var nesting = new Stack<INamedTypeSymbol>();
        for (var outer = type.ContainingType; outer is not null; outer = outer.ContainingType)
            nesting.Push(outer);

        var indent = 1;
        foreach (var outer in nesting)
        {
            sb.Pad(indent).Append(DeclarationKeywords(outer)).Append(' ')
                .Append(outer.Name).Append(TypeParameters(outer)).AppendLine();
            sb.Pad(indent).AppendLine("{");
            indent++;
        }

        sb.Pad(indent).Append(DeclarationKeywords(type)).Append(' ')
            .Append(type.Name).Append(TypeParameters(type)).AppendLine();
        sb.Pad(indent).AppendLine("{");

        foreach (var parameter in primaryCtor.Parameters)
        {
            // Don't fight a property/field the user already declared by hand.
            if (type.GetMembers(parameter.Name).Any(m => m is IPropertySymbol or IFieldSymbol))
                continue;

            sb.Pad(indent + 1)
                .Append("public ")
                .Append(parameter.Type.GetFullyQualifiedName())
                .Append(' ')
                .Append(parameter.Name)
                .Append(" { get; } = ")
                .Append(parameter.Name)
                .AppendLine(";");
        }

        sb.Pad(indent).AppendLine("}");

        for (; indent > 1; indent--)
            sb.Pad(indent - 1).AppendLine("}");

        sb.AppendLine("}");

        context.AddSource(
            type.GetFullyQualifiedName().Replace(":", "").Replace("<", "_").Replace(">", "_").Replace(", ", "_") + ".g.cs",
            sb.ToString());
    }

    // The contextual `partial` keyword must appear immediately before the type
    // keyword, so any other modifiers (readonly/ref) come first.
    static string DeclarationKeywords(INamedTypeSymbol type)
    {
        if (!type.IsValueType)
            return "partial class";

        var sb = new StringBuilder();
        if (type.IsReadOnly)
            sb.Append("readonly ");
        if (type.IsRefLikeType)
            sb.Append("ref ");
        sb.Append("partial struct");
        return sb.ToString();
    }

    static string TypeParameters(INamedTypeSymbol type) =>
        type.TypeParameters.Length == 0
            ? string.Empty
            : "<" + string.Join(", ", type.TypeParameters.Select(p => p.Name)) + ">";
}
