using System;
using System.Collections.Generic;
using Avalonia.Input.Raw;
using Avalonia.Interactivity;
using Avalonia.Metadata;
using Avalonia.Rendering;

namespace Avalonia.Input
{
    public class PointerEventArgs : RoutedEventArgs, IKeyModifiersEventArgs
    {
        private readonly IPresentationSource? _eventPresentationSource; // the original observer of the event
        private readonly Point _presentationSourcePosition;
        private readonly PointerPointProperties _properties;
        private readonly Lazy<IReadOnlyList<RawPointerPoint>?>? _previousPoints;

        public PointerEventArgs(RoutedEvent? routedEvent,
            object? source,
            IPointer pointer,
            Visual? rootVisual, Point rootVisualPosition,
            ulong timestamp,
            PointerPointProperties properties,
            KeyModifiers modifiers)
           : base(routedEvent)
        {
            Source = source;
            _eventPresentationSource = rootVisual?.PresentationSource;
            _presentationSourcePosition = rootVisualPosition;
            _properties = properties;
            Pointer = pointer;
            Timestamp = timestamp;
            KeyModifiers = modifiers;
        }

        [PrivateApi]
        public PointerEventArgs(RoutedEvent? routedEvent,
            object? source,
            IPointer pointer,
            Visual? rootVisual, Point rootVisualPosition,
            ulong timestamp,
            PointerPointProperties properties,
            KeyModifiers modifiers,
            Lazy<IReadOnlyList<RawPointerPoint>?>? previousPoints,
            object? platformInputEventCookie = null)
            : this(routedEvent, source, pointer, rootVisual, rootVisualPosition, timestamp, properties, modifiers)
        {
            _previousPoints = previousPoints;
            PlatformInputEventCookie = platformInputEventCookie;
        }

        /// <summary>
        /// Gets specific pointer generated by input device.
        /// </summary>
        public IPointer Pointer { get; }

        /// <summary>
        /// Gets the time when the input occurred.
        /// </summary>
        public ulong Timestamp { get; }

        /// <summary>
        /// An opaque platform-specific cookie associated with this event.
        /// Used by backends to pass platform data through the input pipeline.
        /// </summary>
        [PrivateApi]
        public object? PlatformInputEventCookie { get; }

        internal bool IsGestureRecognitionSkipped
        {
            get
            {
                return (Pointer as Pointer)?.IsGestureRecognitionSkipped ?? false;
            }
            private set
            {
                if (Pointer is Pointer pointer)
                    pointer.IsGestureRecognitionSkipped = true;
            }
        }

        /// <summary>
        /// Gets a value that indicates which key modifiers were active at the time that the pointer event was initiated.
        /// </summary>
        public KeyModifiers KeyModifiers { get; }

        private Point GetPosition(Point pt, Visual? relativeTo)
        {
            if (relativeTo == null)
                return pt;
            if (_eventPresentationSource == null || relativeTo?.PresentationSource?.RootVisual == null)
                return default;

            if (relativeTo.PresentationSource != _eventPresentationSource)
            {
                if (_eventPresentationSource.PointToScreen(pt) is { } screenPt &&
                    relativeTo.PresentationSource.PointToClient(screenPt) is { } targetClientPt)
                {
                    pt = targetClientPt;
                }
                else
                {
                    return default;
                }
            }

            return relativeTo.PresentationSource.RootVisual.TranslatePoint(pt, relativeTo) ?? default;
        }

        /// <summary>
        /// Gets the pointer position relative to a control.
        /// </summary>
        /// <param name="relativeTo">The visual whose coordinate system to use. Pass null for toplevel coordinate system</param>
        /// <returns>The pointer position in the control's coordinates.</returns>
        public Point GetPosition(Visual? relativeTo) => GetPosition(_presentationSourcePosition, relativeTo);

        /// <summary>
        /// Returns the PointerPoint associated with the current event
        /// </summary>
        /// <param name="relativeTo">The visual whose coordinate system to use. Pass null for toplevel coordinate system</param>
        /// <returns></returns>
        public PointerPoint GetCurrentPoint(Visual? relativeTo)
            => new PointerPoint(Pointer, GetPosition(relativeTo), _properties);

        /// <summary>
        /// Returns the PointerPoint associated with the current event
        /// </summary>
        /// <param name="relativeTo">The visual which coordinate system to use. Pass null for toplevel coordinate system</param>
        /// <returns></returns>
        public IReadOnlyList<PointerPoint> GetIntermediatePoints(Visual? relativeTo)
        {
            var previousPoints = _previousPoints?.Value;
            if (previousPoints == null || previousPoints.Count == 0)
                return new[] { GetCurrentPoint(relativeTo) };
            var points = new PointerPoint[previousPoints.Count + 1];
            for (var c = 0; c < previousPoints.Count; c++)
            {
                var pt = previousPoints[c];
                var pointProperties = new PointerPointProperties(_properties, pt);
                points[c] = new PointerPoint(Pointer, GetPosition(pt.Position, relativeTo), pointProperties);
            }

            points[points.Length - 1] = GetCurrentPoint(relativeTo);
            return points;
        }

        /// <summary>
        /// Prevents this event from being handled by other gesture recognizers in the route
        /// </summary>
        public void PreventGestureRecognition()
        {
            IsGestureRecognitionSkipped = true;
        }

        /// <summary>
        /// Gets the state the pointer device had when this event occurred.
        /// </summary>
        public PointerPointProperties Properties => _properties;
    }

    public enum MouseButton
    {
        None,
        Left,
        Right,
        Middle,
        XButton1,
        XButton2
    }

    public class PointerPressedEventArgs : PointerEventArgs
    {
        public PointerPressedEventArgs(
            object? source,
            IPointer pointer,
            Visual rootVisual, Point rootVisualPosition,
            ulong timestamp,
            PointerPointProperties properties,
            KeyModifiers modifiers,
            int clickCount = 1)
            : base(InputElement.PointerPressedEvent, source, pointer, rootVisual, rootVisualPosition,
                timestamp, properties, modifiers)
        {
            ClickCount = clickCount;
        }

        [PrivateApi]
        public PointerPressedEventArgs(
            object? source,
            IPointer pointer,
            Visual rootVisual, Point rootVisualPosition,
            ulong timestamp,
            PointerPointProperties properties,
            KeyModifiers modifiers,
            int clickCount,
            object? platformInputEventCookie)
            : base(InputElement.PointerPressedEvent, source, pointer, rootVisual, rootVisualPosition,
                timestamp, properties, modifiers, null, platformInputEventCookie)
        {
            ClickCount = clickCount;
        }

        public int ClickCount { get; }
    }

    public class PointerReleasedEventArgs : PointerEventArgs
    {
        public PointerReleasedEventArgs(
            object? source, IPointer pointer,
            Visual rootVisual, Point rootVisualPosition, ulong timestamp,
            PointerPointProperties properties, KeyModifiers modifiers,
            MouseButton initialPressMouseButton)
            : base(InputElement.PointerReleasedEvent, source, pointer, rootVisual, rootVisualPosition,
                timestamp, properties, modifiers)
        {
            InitialPressMouseButton = initialPressMouseButton;
        }

        /// <summary>
        /// Gets the mouse button that triggered the corresponding PointerPressed event
        /// </summary>
        public MouseButton InitialPressMouseButton { get; }
    }

    public class PointerCaptureLostEventArgs : RoutedEventArgs
    {
        public IPointer Pointer { get; }

        public PointerCaptureLostEventArgs(object? source, IPointer pointer) : base(InputElement.PointerCaptureLostEvent)
        {
            Pointer = pointer;
            Source = source;
        }
    }

    internal class PointerCaptureChangingEventArgs : RoutedEventArgs
    {
        public IPointer Pointer { get; }
        public CaptureSource CaptureSource { get; }
        public IInputElement? NewValue { get; }

        internal PointerCaptureChangingEventArgs(object? source, IPointer pointer, IInputElement? newValue, CaptureSource captureSource) : base(InputElement.PointerCaptureChangingEvent)
        {
            Pointer = pointer;
            Source = source;
            NewValue = newValue;
            CaptureSource = captureSource;
        }
    }
}
