//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     GenAPI Version: 7.0.8.6004
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Avalonia
{
    public static partial class Direct2DApplicationExtensions
    {
        public static Avalonia.AppBuilder UseDirect2D1(this Avalonia.AppBuilder builder) { throw null; }
    }
}
namespace Avalonia.Direct2D1
{
    public partial interface IExternalDirect2DRenderTargetSurface
    {
        void AfterDrawing();
        void BeforeDrawing();
        void DestroyRenderTarget();
        SharpDX.Direct2D1.RenderTarget GetOrCreateRenderTarget();
    }
}
