//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     GenAPI Version: 7.0.8.6004
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Tmds.DBus.SourceGenerator
{
    public partial class PropertyChanges<TProperties> : System.IEquatable<Tmds.DBus.SourceGenerator.PropertyChanges<TProperties>>
    {
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        protected PropertyChanges(Tmds.DBus.SourceGenerator.PropertyChanges<TProperties> original) { }
        public PropertyChanges(TProperties Properties, string[] Invalidated, string[] Changed) { }
        public string[] Changed { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        protected virtual System.Type EqualityContract { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } }
        public string[] Invalidated { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
        public TProperties Properties { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public void Deconstruct(out TProperties Properties, out string[] Invalidated, out string[] Changed) { throw null; }
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public override bool Equals(object? obj) { throw null; }
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public virtual bool Equals(Tmds.DBus.SourceGenerator.PropertyChanges<TProperties>? other) { throw null; }
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public override int GetHashCode() { throw null; }
        public bool HasChanged(string property) { throw null; }
        public bool IsInvalidated(string property) { throw null; }
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public static bool operator ==(Tmds.DBus.SourceGenerator.PropertyChanges<TProperties>? left, Tmds.DBus.SourceGenerator.PropertyChanges<TProperties>? right) { throw null; }
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public static bool operator !=(Tmds.DBus.SourceGenerator.PropertyChanges<TProperties>? left, Tmds.DBus.SourceGenerator.PropertyChanges<TProperties>? right) { throw null; }
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        protected virtual bool PrintMembers(System.Text.StringBuilder builder) { throw null; }
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public override string ToString() { throw null; }
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public virtual Tmds.DBus.SourceGenerator.PropertyChanges<TProperties> <Clone>$() { throw null; }
    }
}
