//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     GenAPI Version: 7.0.8.6004
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Avalonia.Win32.Embedding
{
    [System.ComponentModel.ToolboxItemAttribute(true)]
    public partial class WinFormsAvaloniaControlHost : System.Windows.Forms.Control
    {
        public WinFormsAvaloniaControlHost() { }
        public Avalonia.Controls.Control Content { get { throw null; } set { } }
        protected override void Dispose(bool disposing) { }
        protected override void OnGotFocus(System.EventArgs e) { }
        protected override void OnPaint(System.Windows.Forms.PaintEventArgs e) { }
        protected override void OnResize(System.EventArgs e) { }
    }
}
namespace Avalonia.Win32.Interop.Wpf
{
    [System.Windows.Markup.ContentPropertyAttribute("Content")]
    public partial class WpfAvaloniaHost : System.Windows.FrameworkElement, System.IDisposable, System.Windows.Markup.IAddChild
    {
        public WpfAvaloniaHost() { }
        public object Content { get { throw null; } set { } }
        protected override int VisualChildrenCount { get { throw null; } }
        protected override System.Windows.Size ArrangeOverride(System.Windows.Size arrangeSize) { throw null; }
        public void Dispose() { }
        ~WpfAvaloniaHost() { }
        protected override System.Windows.Media.Visual GetVisualChild(int index) { throw null; }
        protected override System.Windows.Size MeasureOverride(System.Windows.Size constraint) { throw null; }
        void System.Windows.Markup.IAddChild.AddChild(object value) { }
        void System.Windows.Markup.IAddChild.AddText(string text) { }
    }
}
