//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     GenAPI Version: 7.0.8.6004
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Avalonia.Themes.Fluent
{
    public partial class ColorPaletteResources : Avalonia.AvaloniaObject, Avalonia.Controls.IResourceNode
    {
        public static readonly Avalonia.DirectProperty<Avalonia.Themes.Fluent.ColorPaletteResources, Avalonia.Media.Color> AccentProperty;
        public ColorPaletteResources() { }
        public Avalonia.Media.Color Accent { get { throw null; } set { } }
        public Avalonia.Media.Color AltHigh { get { throw null; } set { } }
        public Avalonia.Media.Color AltLow { get { throw null; } set { } }
        public Avalonia.Media.Color AltMedium { get { throw null; } set { } }
        public Avalonia.Media.Color AltMediumHigh { get { throw null; } set { } }
        public Avalonia.Media.Color AltMediumLow { get { throw null; } set { } }
        public Avalonia.Media.Color BaseHigh { get { throw null; } set { } }
        public Avalonia.Media.Color BaseLow { get { throw null; } set { } }
        public Avalonia.Media.Color BaseMedium { get { throw null; } set { } }
        public Avalonia.Media.Color BaseMediumHigh { get { throw null; } set { } }
        public Avalonia.Media.Color BaseMediumLow { get { throw null; } set { } }
        public Avalonia.Media.Color ChromeAltLow { get { throw null; } set { } }
        public Avalonia.Media.Color ChromeBlackHigh { get { throw null; } set { } }
        public Avalonia.Media.Color ChromeBlackLow { get { throw null; } set { } }
        public Avalonia.Media.Color ChromeBlackMedium { get { throw null; } set { } }
        public Avalonia.Media.Color ChromeBlackMediumLow { get { throw null; } set { } }
        public Avalonia.Media.Color ChromeDisabledHigh { get { throw null; } set { } }
        public Avalonia.Media.Color ChromeDisabledLow { get { throw null; } set { } }
        public Avalonia.Media.Color ChromeGray { get { throw null; } set { } }
        public Avalonia.Media.Color ChromeHigh { get { throw null; } set { } }
        public Avalonia.Media.Color ChromeLow { get { throw null; } set { } }
        public Avalonia.Media.Color ChromeMedium { get { throw null; } set { } }
        public Avalonia.Media.Color ChromeMediumLow { get { throw null; } set { } }
        public Avalonia.Media.Color ChromeWhite { get { throw null; } set { } }
        public Avalonia.Media.Color ErrorText { get { throw null; } set { } }
        public bool HasResources { get { throw null; } }
        public Avalonia.Media.Color ListLow { get { throw null; } set { } }
        public Avalonia.Media.Color ListMedium { get { throw null; } set { } }
        public Avalonia.Media.Color RegionColor { get { throw null; } set { } }
        protected override void OnPropertyChanged(Avalonia.AvaloniaPropertyChangedEventArgs change) { }
        public bool TryGetResource(object key, Avalonia.Styling.ThemeVariant? theme, out object? value) { throw null; }
    }
    public enum DensityStyle
    {
        Normal = 0,
        Compact = 1,
    }
    public partial class FluentTheme : Avalonia.Styling.Styles
    {
        public static readonly Avalonia.StyledProperty<Avalonia.Themes.Fluent.DensityStyle> DensityStyleProperty;
        public FluentTheme(System.IServiceProvider? sp = null) { }
        public Avalonia.Themes.Fluent.DensityStyle DensityStyle { get { throw null; } set { } }
        public System.Collections.Generic.IDictionary<Avalonia.Styling.ThemeVariant, Avalonia.Themes.Fluent.ColorPaletteResources> Palettes { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } }
        protected override void OnPropertyChanged(Avalonia.AvaloniaPropertyChangedEventArgs change) { }
    }
}
namespace CompiledAvaloniaXaml
{
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    public partial class !AvaloniaResources
    {
        internal !AvaloniaResources() { }
        public static Avalonia.Controls.ResourceDictionary Build:/Accents/BaseColorsPalette.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Accents/BaseResources.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Accents/FluentControlResources.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Controls/AdornerLayer.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Controls/AutoCompleteBox.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Controls/Button.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Controls/ButtonSpinner.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Controls/Calendar.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Controls/CalendarButton.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Controls/CalendarDatePicker.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Controls/CalendarDayButton.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Controls/CalendarItem.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Controls/CaptionButtons.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Controls/Carousel.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Controls/CheckBox.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Controls/ComboBox.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Controls/ComboBoxItem.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Controls/ContentControl.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Controls/ContextMenu.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Controls/DataValidationErrors.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Controls/DatePicker.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Controls/DateTimePickerShared.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Controls/DropDownButton.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Controls/EmbeddableControlRoot.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Controls/Expander.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Styling.Styles Build:/Controls/FluentControls.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Controls/FlyoutPresenter.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Controls/GridSplitter.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Controls/ItemsControl.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Controls/Label.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Controls/ListBox.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Controls/ListBoxItem.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Controls/ManagedFileChooser.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Controls/Menu.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Controls/MenuFlyoutPresenter.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Controls/MenuItem.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Controls/MenuScrollViewer.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Controls/NativeMenuBar.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Controls/NotificationCard.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Controls/NumericUpDown.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Controls/OverlayPopupHost.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Controls/PathIcon.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Controls/PopupRoot.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Controls/ProgressBar.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Controls/RadioButton.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Controls/RefreshContainer.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Controls/RefreshVisualizer.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Controls/RepeatButton.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Controls/ScrollBar.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Controls/ScrollViewer.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Controls/SelectableTextBlock.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Controls/Separator.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Controls/Slider.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Controls/SplitButton.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Controls/SplitView.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Controls/TabControl.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Controls/TabItem.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Controls/TabStrip.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Controls/TabStripItem.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Controls/TextBox.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Controls/ThemeVariantScope.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Controls/TimePicker.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Controls/TitleBar.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Controls/ToggleButton.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Controls/ToggleSwitch.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Controls/ToolTip.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Controls/TransitioningContentControl.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Controls/TreeView.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Controls/TreeViewItem.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Styling.Style Build:/Controls/UserControl.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Controls/Window.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Controls.ResourceDictionary Build:/Controls/WindowNotificationManager.xaml(System.IServiceProvider ) { throw null; }
        public static Avalonia.Styling.Styles Build:/DensityStyles/Compact.xaml(System.IServiceProvider ) { throw null; }
        public static void Populate:/Accents/BaseColorsPalette.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Accents/BaseResources.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Accents/FluentControlResources.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Controls/AdornerLayer.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Controls/AutoCompleteBox.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Controls/Button.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Controls/ButtonSpinner.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Controls/Calendar.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Controls/CalendarButton.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Controls/CalendarDatePicker.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Controls/CalendarDayButton.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Controls/CalendarItem.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Controls/CaptionButtons.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Controls/Carousel.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Controls/CheckBox.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Controls/ComboBox.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Controls/ComboBoxItem.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Controls/ContentControl.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Controls/ContextMenu.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Controls/DataValidationErrors.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Controls/DatePicker.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Controls/DateTimePickerShared.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Controls/DropDownButton.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Controls/EmbeddableControlRoot.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Controls/Expander.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Controls/FluentControls.xaml(System.IServiceProvider , Avalonia.Styling.Styles ) { }
        public static void Populate:/Controls/FlyoutPresenter.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Controls/GridSplitter.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Controls/ItemsControl.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Controls/Label.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Controls/ListBox.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Controls/ListBoxItem.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Controls/ManagedFileChooser.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Controls/Menu.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Controls/MenuFlyoutPresenter.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Controls/MenuItem.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Controls/MenuScrollViewer.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Controls/NativeMenuBar.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Controls/NotificationCard.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Controls/NumericUpDown.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Controls/OverlayPopupHost.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Controls/PathIcon.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Controls/PopupRoot.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Controls/ProgressBar.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Controls/RadioButton.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Controls/RefreshContainer.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Controls/RefreshVisualizer.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Controls/RepeatButton.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Controls/ScrollBar.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Controls/ScrollViewer.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Controls/SelectableTextBlock.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Controls/Separator.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Controls/Slider.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Controls/SplitButton.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Controls/SplitView.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Controls/TabControl.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Controls/TabItem.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Controls/TabStrip.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Controls/TabStripItem.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Controls/TextBox.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Controls/ThemeVariantScope.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Controls/TimePicker.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Controls/TitleBar.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Controls/ToggleButton.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Controls/ToggleSwitch.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Controls/ToolTip.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Controls/TransitioningContentControl.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Controls/TreeView.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Controls/TreeViewItem.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Controls/UserControl.xaml(System.IServiceProvider , Avalonia.Styling.Style ) { }
        public static void Populate:/Controls/Window.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/Controls/WindowNotificationManager.xaml(System.IServiceProvider , Avalonia.Controls.ResourceDictionary ) { }
        public static void Populate:/DensityStyles/Compact.xaml(System.IServiceProvider , Avalonia.Styling.Styles ) { }
        public partial class NamespaceInfo:/Accents/BaseColorsPalette.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Accents/BaseColorsPalette.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Accents/BaseResources.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Accents/BaseResources.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Accents/FluentControlResources.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Accents/FluentControlResources.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/AdornerLayer.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/AdornerLayer.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/AutoCompleteBox.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/AutoCompleteBox.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/Button.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/Button.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/ButtonSpinner.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/ButtonSpinner.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/Calendar.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/Calendar.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/CalendarButton.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/CalendarButton.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/CalendarDatePicker.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/CalendarDatePicker.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/CalendarDayButton.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/CalendarDayButton.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/CalendarItem.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/CalendarItem.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/CaptionButtons.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/CaptionButtons.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/Carousel.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/Carousel.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/CheckBox.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/CheckBox.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/ComboBox.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/ComboBox.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/ComboBoxItem.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/ComboBoxItem.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/ContentControl.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/ContentControl.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/ContextMenu.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/ContextMenu.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/DataValidationErrors.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/DataValidationErrors.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/DatePicker.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/DatePicker.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/DateTimePickerShared.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/DateTimePickerShared.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/DropDownButton.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/DropDownButton.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/EmbeddableControlRoot.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/EmbeddableControlRoot.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/Expander.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/Expander.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/FluentControls.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/FluentControls.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/FlyoutPresenter.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/FlyoutPresenter.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/GridSplitter.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/GridSplitter.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/ItemsControl.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/ItemsControl.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/Label.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/Label.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/ListBox.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/ListBox.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/ListBoxItem.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/ListBoxItem.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/ManagedFileChooser.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/ManagedFileChooser.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/Menu.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/Menu.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/MenuFlyoutPresenter.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/MenuFlyoutPresenter.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/MenuItem.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/MenuItem.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/MenuScrollViewer.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/MenuScrollViewer.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/NativeMenuBar.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/NativeMenuBar.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/NotificationCard.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/NotificationCard.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/NumericUpDown.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/NumericUpDown.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/OverlayPopupHost.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/OverlayPopupHost.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/PathIcon.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/PathIcon.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/PopupRoot.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/PopupRoot.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/ProgressBar.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/ProgressBar.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/RadioButton.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/RadioButton.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/RefreshContainer.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/RefreshContainer.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/RefreshVisualizer.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/RefreshVisualizer.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/RepeatButton.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/RepeatButton.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/ScrollBar.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/ScrollBar.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/ScrollViewer.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/ScrollViewer.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/SelectableTextBlock.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/SelectableTextBlock.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/Separator.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/Separator.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/Slider.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/Slider.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/SplitButton.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/SplitButton.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/SplitView.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/SplitView.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/TabControl.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/TabControl.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/TabItem.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/TabItem.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/TabStrip.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/TabStrip.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/TabStripItem.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/TabStripItem.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/TextBox.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/TextBox.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/ThemeVariantScope.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/ThemeVariantScope.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/TimePicker.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/TimePicker.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/TitleBar.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/TitleBar.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/ToggleButton.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/ToggleButton.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/ToggleSwitch.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/ToggleSwitch.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/ToolTip.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/ToolTip.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/TransitioningContentControl.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/TransitioningContentControl.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/TreeView.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/TreeView.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/TreeViewItem.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/TreeViewItem.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/UserControl.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/UserControl.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/Window.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/Window.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/Controls/WindowNotificationManager.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/Controls/WindowNotificationManager.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/DensityStyles/Compact.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/DensityStyles/Compact.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
        public partial class NamespaceInfo:/FluentTheme.xaml : Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider
        {
            public static Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlXmlNamespaceInfoProvider Singleton;
            public NamespaceInfo:/FluentTheme.xaml() { }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> XmlNamespaces { get { throw null; } }
            public virtual System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<Avalonia.Markup.Xaml.XamlIl.Runtime.AvaloniaXamlIlXmlNamespaceInfo>> get_XmlNamespaces() { throw null; }
        }
    }
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    public partial class !XamlLoader
    {
        internal !XamlLoader() { }
        public static object TryLoad(System.IServiceProvider , string ) { throw null; }
        public static object TryLoad(string ) { throw null; }
    }
}
