//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     GenAPI Version: 7.0.8.6004
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Avalonia.Remote.Protocol
{
    [System.AttributeUsageAttribute(System.AttributeTargets.Class)]
    public sealed partial class AvaloniaRemoteMessageGuidAttribute : System.Attribute
    {
        public AvaloniaRemoteMessageGuidAttribute(string guid) { }
        public System.Guid Guid { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } }
    }
    [System.Diagnostics.CodeAnalysis.RequiresUnreferencedCodeAttribute("Bson uses reflection")]
    public partial class BsonTcpTransport : Avalonia.Remote.Protocol.TcpTransportBase
    {
        public BsonTcpTransport() : base (default(Avalonia.Remote.Protocol.IMessageTypeResolver)) { }
        public BsonTcpTransport(Avalonia.Remote.Protocol.IMessageTypeResolver resolver) : base (default(Avalonia.Remote.Protocol.IMessageTypeResolver)) { }
        protected override Avalonia.Remote.Protocol.IAvaloniaRemoteTransportConnection CreateTransport(Avalonia.Remote.Protocol.IMessageTypeResolver resolver, System.IO.Stream stream, System.Action dispose) { throw null; }
    }
    public partial class DefaultMessageTypeResolver : Avalonia.Remote.Protocol.IMessageTypeResolver
    {
        [System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessageAttribute("Trimming", "IL2026", Justification="If type was trimmed, we don't need to resolve it in the remove protocol")]
        public DefaultMessageTypeResolver(params System.Reflection.Assembly[] assemblies) { }
        public System.Type GetByGuid(System.Guid id) { throw null; }
        public System.Guid GetGuid(System.Type type) { throw null; }
    }
    [Avalonia.Remote.Protocol.AvaloniaRemoteMessageGuidAttribute("53778004-78fa-4381-8ec3-176a6f2328b6")]
    public partial class HtmlTransportStartedMessage
    {
        public HtmlTransportStartedMessage() { }
        public string Uri { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
    }
    public partial interface IAvaloniaRemoteTransportConnection : System.IDisposable
    {
        event System.Action<Avalonia.Remote.Protocol.IAvaloniaRemoteTransportConnection, System.Exception> OnException;
        event System.Action<Avalonia.Remote.Protocol.IAvaloniaRemoteTransportConnection, object> OnMessage;
        System.Threading.Tasks.Task Send(object data);
        void Start();
    }
    public partial interface IMessageTypeResolver
    {
        System.Type GetByGuid(System.Guid id);
        System.Guid GetGuid(System.Type type);
    }
    public abstract partial class TcpTransportBase
    {
        public TcpTransportBase(Avalonia.Remote.Protocol.IMessageTypeResolver resolver) { }
        public System.Threading.Tasks.Task<Avalonia.Remote.Protocol.IAvaloniaRemoteTransportConnection> Connect(System.Net.IPAddress address, int port) { throw null; }
        protected abstract Avalonia.Remote.Protocol.IAvaloniaRemoteTransportConnection CreateTransport(Avalonia.Remote.Protocol.IMessageTypeResolver resolver, System.IO.Stream stream, System.Action disposeCallback);
        public System.IDisposable Listen(System.Net.IPAddress address, int port, System.Action<Avalonia.Remote.Protocol.IAvaloniaRemoteTransportConnection> cb) { throw null; }
    }
    public partial class TransportConnectionWrapper : Avalonia.Remote.Protocol.IAvaloniaRemoteTransportConnection, System.IDisposable
    {
        public TransportConnectionWrapper(Avalonia.Remote.Protocol.IAvaloniaRemoteTransportConnection conn) { }
        public event System.Action<Avalonia.Remote.Protocol.IAvaloniaRemoteTransportConnection, System.Exception> OnException { add { } remove { } }
        public event System.Action<Avalonia.Remote.Protocol.IAvaloniaRemoteTransportConnection, object> OnMessage { add { } remove { } }
        public void Dispose() { }
        public System.Threading.Tasks.Task Send(object data) { throw null; }
        public void Start() { }
    }
}
namespace Avalonia.Remote.Protocol.Designer
{
    public partial class ExceptionDetails
    {
        public ExceptionDetails() { }
        public ExceptionDetails(System.Exception e) { }
        public string ExceptionType { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
        public int? LineNumber { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
        public int? LinePosition { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
        public string Message { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
    }
    [Avalonia.Remote.Protocol.AvaloniaRemoteMessageGuidAttribute("854887CF-2694-4EB6-B499-7461B6FB96C7")]
    public partial class StartDesignerSessionMessage
    {
        public StartDesignerSessionMessage() { }
        public string SessionId { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
    }
    [Avalonia.Remote.Protocol.AvaloniaRemoteMessageGuidAttribute("9AEC9A2E-6315-4066-B4BA-E9A9EFD0F8CC")]
    public partial class UpdateXamlMessage
    {
        public UpdateXamlMessage() { }
        public string AssemblyPath { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
        public string Xaml { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
        public string XamlFileProjectPath { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
    }
    [Avalonia.Remote.Protocol.AvaloniaRemoteMessageGuidAttribute("B7A70093-0C5D-47FD-9261-22086D43A2E2")]
    public partial class UpdateXamlResultMessage
    {
        public UpdateXamlResultMessage() { }
        public string Error { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
        public Avalonia.Remote.Protocol.Designer.ExceptionDetails Exception { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
        public string Handle { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
    }
}
namespace Avalonia.Remote.Protocol.Input
{
    public abstract partial class InputEventMessageBase
    {
        protected InputEventMessageBase() { }
        public Avalonia.Remote.Protocol.Input.InputModifiers[] Modifiers { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
    }
    [System.FlagsAttribute]
    public enum InputModifiers
    {
        Alt = 0,
        Control = 1,
        Shift = 2,
        Windows = 3,
        LeftMouseButton = 4,
        RightMouseButton = 5,
        MiddleMouseButton = 6,
    }
    public enum Key
    {
        None = 0,
        Cancel = 1,
        Back = 2,
        Tab = 3,
        LineFeed = 4,
        Clear = 5,
        Enter = 6,
        Return = 6,
        Pause = 7,
        Capital = 8,
        CapsLock = 8,
        HangulMode = 9,
        KanaMode = 9,
        JunjaMode = 10,
        FinalMode = 11,
        HanjaMode = 12,
        KanjiMode = 12,
        Escape = 13,
        ImeConvert = 14,
        ImeNonConvert = 15,
        ImeAccept = 16,
        ImeModeChange = 17,
        Space = 18,
        PageUp = 19,
        Prior = 19,
        Next = 20,
        PageDown = 20,
        End = 21,
        Home = 22,
        Left = 23,
        Up = 24,
        Right = 25,
        Down = 26,
        Select = 27,
        Print = 28,
        Execute = 29,
        PrintScreen = 30,
        Snapshot = 30,
        Insert = 31,
        Delete = 32,
        Help = 33,
        D0 = 34,
        D1 = 35,
        D2 = 36,
        D3 = 37,
        D4 = 38,
        D5 = 39,
        D6 = 40,
        D7 = 41,
        D8 = 42,
        D9 = 43,
        A = 44,
        B = 45,
        C = 46,
        D = 47,
        E = 48,
        F = 49,
        G = 50,
        H = 51,
        I = 52,
        J = 53,
        K = 54,
        L = 55,
        M = 56,
        N = 57,
        O = 58,
        P = 59,
        Q = 60,
        R = 61,
        S = 62,
        T = 63,
        U = 64,
        V = 65,
        W = 66,
        X = 67,
        Y = 68,
        Z = 69,
        LWin = 70,
        RWin = 71,
        Apps = 72,
        Sleep = 73,
        NumPad0 = 74,
        NumPad1 = 75,
        NumPad2 = 76,
        NumPad3 = 77,
        NumPad4 = 78,
        NumPad5 = 79,
        NumPad6 = 80,
        NumPad7 = 81,
        NumPad8 = 82,
        NumPad9 = 83,
        Multiply = 84,
        Add = 85,
        Separator = 86,
        Subtract = 87,
        Decimal = 88,
        Divide = 89,
        F1 = 90,
        F2 = 91,
        F3 = 92,
        F4 = 93,
        F5 = 94,
        F6 = 95,
        F7 = 96,
        F8 = 97,
        F9 = 98,
        F10 = 99,
        F11 = 100,
        F12 = 101,
        F13 = 102,
        F14 = 103,
        F15 = 104,
        F16 = 105,
        F17 = 106,
        F18 = 107,
        F19 = 108,
        F20 = 109,
        F21 = 110,
        F22 = 111,
        F23 = 112,
        F24 = 113,
        NumLock = 114,
        Scroll = 115,
        LeftShift = 116,
        RightShift = 117,
        LeftCtrl = 118,
        RightCtrl = 119,
        LeftAlt = 120,
        RightAlt = 121,
        BrowserBack = 122,
        BrowserForward = 123,
        BrowserRefresh = 124,
        BrowserStop = 125,
        BrowserSearch = 126,
        BrowserFavorites = 127,
        BrowserHome = 128,
        VolumeMute = 129,
        VolumeDown = 130,
        VolumeUp = 131,
        MediaNextTrack = 132,
        MediaPreviousTrack = 133,
        MediaStop = 134,
        MediaPlayPause = 135,
        LaunchMail = 136,
        SelectMedia = 137,
        LaunchApplication1 = 138,
        LaunchApplication2 = 139,
        Oem1 = 140,
        OemSemicolon = 140,
        OemPlus = 141,
        OemComma = 142,
        OemMinus = 143,
        OemPeriod = 144,
        Oem2 = 145,
        OemQuestion = 145,
        Oem3 = 146,
        OemTilde = 146,
        AbntC1 = 147,
        AbntC2 = 148,
        Oem4 = 149,
        OemOpenBrackets = 149,
        Oem5 = 150,
        OemPipe = 150,
        Oem6 = 151,
        OemCloseBrackets = 151,
        Oem7 = 152,
        OemQuotes = 152,
        Oem8 = 153,
        Oem102 = 154,
        OemBackslash = 154,
        ImeProcessed = 155,
        System = 156,
        DbeAlphanumeric = 157,
        OemAttn = 157,
        DbeKatakana = 158,
        OemFinish = 158,
        DbeHiragana = 159,
        OemCopy = 159,
        DbeSbcsChar = 160,
        OemAuto = 160,
        DbeDbcsChar = 161,
        OemEnlw = 161,
        DbeRoman = 162,
        OemBackTab = 162,
        Attn = 163,
        DbeNoRoman = 163,
        CrSel = 164,
        DbeEnterWordRegisterMode = 164,
        DbeEnterImeConfigureMode = 165,
        ExSel = 165,
        DbeFlushString = 166,
        EraseEof = 166,
        DbeCodeInput = 167,
        Play = 167,
        DbeNoCodeInput = 168,
        Zoom = 168,
        DbeDetermineString = 169,
        NoName = 169,
        DbeEnterDialogConversionMode = 170,
        Pa1 = 170,
        OemClear = 171,
        DeadCharProcessed = 172,
        FnLeftArrow = 10001,
        FnRightArrow = 10002,
        FnUpArrow = 10003,
        FnDownArrow = 10004,
    }
    [Avalonia.Remote.Protocol.AvaloniaRemoteMessageGuidAttribute("1C3B691E-3D54-4237-BFB0-9FEA83BC1DB8")]
    public partial class KeyEventMessage : Avalonia.Remote.Protocol.Input.InputEventMessageBase
    {
        public KeyEventMessage() { }
        public bool IsDown { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
        public Avalonia.Remote.Protocol.Input.Key Key { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
    }
    public enum MouseButton
    {
        None = 0,
        Left = 1,
        Right = 2,
        Middle = 3,
    }
    public abstract partial class PointerEventMessageBase : Avalonia.Remote.Protocol.Input.InputEventMessageBase
    {
        protected PointerEventMessageBase() { }
        public double X { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
        public double Y { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
    }
    [Avalonia.Remote.Protocol.AvaloniaRemoteMessageGuidAttribute("6228F0B9-99F2-4F62-A621-414DA2881648")]
    public partial class PointerMovedEventMessage : Avalonia.Remote.Protocol.Input.PointerEventMessageBase
    {
        public PointerMovedEventMessage() { }
    }
    [Avalonia.Remote.Protocol.AvaloniaRemoteMessageGuidAttribute("7E9E2818-F93F-411A-800E-6B1AEB11DA46")]
    public partial class PointerPressedEventMessage : Avalonia.Remote.Protocol.Input.PointerEventMessageBase
    {
        public PointerPressedEventMessage() { }
        public Avalonia.Remote.Protocol.Input.MouseButton Button { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
    }
    [Avalonia.Remote.Protocol.AvaloniaRemoteMessageGuidAttribute("4ADC84EE-E7C8-4BCF-986C-DE3A2F78EDE4")]
    public partial class PointerReleasedEventMessage : Avalonia.Remote.Protocol.Input.PointerEventMessageBase
    {
        public PointerReleasedEventMessage() { }
        public Avalonia.Remote.Protocol.Input.MouseButton Button { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
    }
    [Avalonia.Remote.Protocol.AvaloniaRemoteMessageGuidAttribute("79301A05-F02D-4B90-BB39-472563B504AE")]
    public partial class ScrollEventMessage : Avalonia.Remote.Protocol.Input.PointerEventMessageBase
    {
        public ScrollEventMessage() { }
        public double DeltaX { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
        public double DeltaY { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
    }
    [Avalonia.Remote.Protocol.AvaloniaRemoteMessageGuidAttribute("C174102E-7405-4594-916F-B10B8248A17D")]
    public partial class TextInputEventMessage : Avalonia.Remote.Protocol.Input.InputEventMessageBase
    {
        public TextInputEventMessage() { }
        public string Text { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
    }
}
namespace Avalonia.Remote.Protocol.Viewport
{
    [Avalonia.Remote.Protocol.AvaloniaRemoteMessageGuidAttribute("7A3c25d3-3652-438D-8EF1-86E942CC96C0")]
    public partial class ClientRenderInfoMessage
    {
        public ClientRenderInfoMessage() { }
        public double DpiX { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
        public double DpiY { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
    }
    [Avalonia.Remote.Protocol.AvaloniaRemoteMessageGuidAttribute("63481025-7016-43FE-BADC-F2FD0F88609E")]
    public partial class ClientSupportedPixelFormatsMessage
    {
        public ClientSupportedPixelFormatsMessage() { }
        public Avalonia.Remote.Protocol.Viewport.PixelFormat[] Formats { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
    }
    [Avalonia.Remote.Protocol.AvaloniaRemoteMessageGuidAttribute("BD7A8DE6-3DB8-4A13-8583-D6D4AB189A31")]
    public partial class ClientViewportAllocatedMessage
    {
        public ClientViewportAllocatedMessage() { }
        public double DpiX { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
        public double DpiY { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
        public double Height { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
        public double Width { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
    }
    [Avalonia.Remote.Protocol.AvaloniaRemoteMessageGuidAttribute("F58313EE-FE69-4536-819D-F52EDF201A0E")]
    public partial class FrameMessage
    {
        public FrameMessage() { }
        public byte[] Data { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
        public double DpiX { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
        public double DpiY { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
        public Avalonia.Remote.Protocol.Viewport.PixelFormat Format { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
        public int Height { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
        public long SequenceId { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
        public int Stride { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
        public int Width { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
    }
    [Avalonia.Remote.Protocol.AvaloniaRemoteMessageGuidAttribute("68014F8A-289D-4851-8D34-5367EDA7F827")]
    public partial class FrameReceivedMessage
    {
        public FrameReceivedMessage() { }
        public long SequenceId { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
    }
    [Avalonia.Remote.Protocol.AvaloniaRemoteMessageGuidAttribute("6E3C5310-E2B1-4C3D-8688-01183AA48C5B")]
    public partial class MeasureViewportMessage
    {
        public MeasureViewportMessage() { }
        public double Height { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
        public double Width { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
    }
    public enum PixelFormat
    {
        Rgb565 = 0,
        Rgba8888 = 1,
        Bgra8888 = 2,
        MaxValue = 2,
    }
    [Avalonia.Remote.Protocol.AvaloniaRemoteMessageGuidAttribute("9B47B3D8-61DF-4C38-ACD4-8C1BB72554AC")]
    public partial class RequestViewportResizeMessage
    {
        public RequestViewportResizeMessage() { }
        public double Height { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
        public double Width { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
    }
}
namespace Metsys.Bson
{
    public static partial class Helper
    {
        public static readonly System.DateTime Epoch;
    }
    public partial interface IExpando
    {
        System.Collections.Generic.IDictionary<string, object> Expando { get; }
    }
}
namespace Metsys.Bson.Configuration
{
    public static partial class ExpressionHelper
    {
        public static System.Linq.Expressions.MemberExpression GetMemberExpression<T, TValue>(this System.Linq.Expressions.Expression<System.Func<T, TValue>> expression) { throw null; }
        public static string GetName(this System.Linq.Expressions.MemberExpression expression) { throw null; }
    }
    public partial interface ITypeConfiguration<T>
    {
        Metsys.Bson.Configuration.ITypeConfiguration<T> Ignore(System.Linq.Expressions.Expression<System.Func<T, object>> expression);
        Metsys.Bson.Configuration.ITypeConfiguration<T> Ignore(string name);
        Metsys.Bson.Configuration.ITypeConfiguration<T> IgnoreIfNull(System.Linq.Expressions.Expression<System.Func<T, object>> expression);
        Metsys.Bson.Configuration.ITypeConfiguration<T> UseAlias(System.Linq.Expressions.Expression<System.Func<T, object>> expression, string alias);
    }
}
